services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Minsk
    env_file:
      - .env
    depends_on:
      - db
